/*
 *  Copyright (C) 2010 sviro
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cz.cuni.mff.ksi.jinfer.crudemdl.properties;

import cz.cuni.mff.ksi.jinfer.base.objects.AbstractPropertiesPanel;
import cz.cuni.mff.ksi.jinfer.base.utils.ModuleSelectionHelper;
import cz.cuni.mff.ksi.jinfer.crudemdl.clustering.ClustererFactory;
import cz.cuni.mff.ksi.jinfer.crudemdl.processing.ClusterProcessorFactory;
import java.util.List;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author sviro
 */
public class TwoStepPropertiesPanel extends AbstractPropertiesPanel {

  public static final String NAME = "TwoStepSimplifier";
  public static final String PROPERTIES_CLUSTERER = "clusterer";
  public static final String PROPERTIES_CLUSTER_PROCESSOR = "cluster-processor";
  private static final String DEFAULT_MENU_TEXT = "<none available>";
  private static final long serialVersionUID = 784463431L;

  /** Creates new form ModuleSelectionJPanel */
  public TwoStepPropertiesPanel(final Properties properties) {
    super(properties);
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    labelClusterer = new javax.swing.JLabel();
    clusterer = new javax.swing.JComboBox();
    jScrollPane3 = new javax.swing.JScrollPane();
    descClusterer = new javax.swing.JTextPane();
    labelClusterProcessor = new javax.swing.JLabel();
    clusterProcessor = new javax.swing.JComboBox();
    jScrollPane1 = new javax.swing.JScrollPane();
    descClusterProcessor = new javax.swing.JTextPane();

    setMinimumSize(new java.awt.Dimension(600, 62));
    setPreferredSize(new java.awt.Dimension(600, 62));
    setLayout(new java.awt.GridBagLayout());

    labelClusterer.setText(org.openide.util.NbBundle.getMessage(TwoStepPropertiesPanel.class, "TwoStepPropertiesPanel.labelClusterer.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 12);
    add(labelClusterer, gridBagConstraints);

    clusterer.setMinimumSize(new java.awt.Dimension(400, 22));
    clusterer.setPreferredSize(new java.awt.Dimension(400, 22));
    clusterer.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clustererChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 2);
    add(clusterer, gridBagConstraints);

    jScrollPane3.setViewportView(descClusterer);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipady = 150;
    add(jScrollPane3, gridBagConstraints);

    labelClusterProcessor.setText(org.openide.util.NbBundle.getMessage(TwoStepPropertiesPanel.class, "TwoStepPropertiesPanel.labelClusterProcessor.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 12);
    add(labelClusterProcessor, gridBagConstraints);

    clusterProcessor.setMinimumSize(new java.awt.Dimension(400, 22));
    clusterProcessor.setPreferredSize(new java.awt.Dimension(400, 22));
    clusterProcessor.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clusterProcessorChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 2);
    add(clusterProcessor, gridBagConstraints);

    jScrollPane1.setMinimumSize(null);
    jScrollPane1.setPreferredSize(null);

    descClusterProcessor.setMinimumSize(null);
    descClusterProcessor.setPreferredSize(null);
    jScrollPane1.setViewportView(descClusterProcessor);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipady = 150;
    add(jScrollPane1, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void clustererChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clustererChanged
    // TODO add your handling code here:
    descClusterer.setText(
            ModuleSelectionHelper.lookupImpl(ClustererFactory.class,
            (String) clusterer.getSelectedItem()).getModuleDescription()
            );
  }//GEN-LAST:event_clustererChanged

  private void clusterProcessorChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clusterProcessorChanged
    // TODO add your handling code here:
    descClusterProcessor.setText(
            ModuleSelectionHelper.lookupImpl(ClusterProcessorFactory.class,
            (String) clusterProcessor.getSelectedItem()).getModuleDescription()
            );
  }//GEN-LAST:event_clusterProcessorChanged

  @Override
  public final void load() {
    clusterer.setModel(new DefaultComboBoxModel(
            ModuleSelectionHelper.lookupNames(ClustererFactory.class).toArray()
            ));
    clusterProcessor.setModel(new DefaultComboBoxModel(
           ModuleSelectionHelper.lookupNames(ClusterProcessorFactory.class).toArray()
           ));

    clusterer.setSelectedItem(properties.getProperty(PROPERTIES_CLUSTERER, DEFAULT_MENU_TEXT));
    clusterProcessor.setSelectedItem(properties.getProperty(PROPERTIES_CLUSTER_PROCESSOR,
            DEFAULT_MENU_TEXT));
  }

  @Override
  public void store() {
    properties.setProperty(PROPERTIES_CLUSTERER,
            (String) clusterer.getSelectedItem());
    properties.setProperty(PROPERTIES_CLUSTER_PROCESSOR,
            (String) clusterProcessor.getSelectedItem());
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox clusterProcessor;
  private javax.swing.JComboBox clusterer;
  private javax.swing.JTextPane descClusterProcessor;
  private javax.swing.JTextPane descClusterer;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JLabel labelClusterProcessor;
  private javax.swing.JLabel labelClusterer;
  // End of variables declaration//GEN-END:variables
}
