/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.cuni.mff.ksi.jinfer.ModuleSelector;

import cz.cuni.mff.ksi.jinfer.base.interfaces.IGGenerator;
import cz.cuni.mff.ksi.jinfer.base.interfaces.IGGeneratorCallback;
import cz.cuni.mff.ksi.jinfer.base.interfaces.ModuleSelection;
import cz.cuni.mff.ksi.jinfer.base.interfaces.SchemaGenerator;
import cz.cuni.mff.ksi.jinfer.base.interfaces.SchemaGeneratorCallback;
import cz.cuni.mff.ksi.jinfer.base.interfaces.Simplifier;
import cz.cuni.mff.ksi.jinfer.base.interfaces.SimplifierCallback;
import cz.cuni.mff.ksi.jinfer.base.objects.AbstractNode;
import cz.cuni.mff.ksi.jinfer.base.objects.Input;
import java.util.ArrayList;
import java.util.List;
import org.openide.util.Lookup;
import org.openide.util.NbPreferences;
import org.openide.util.lookup.Lookups;

final class JinferOPTPanel extends javax.swing.JPanel implements ModuleSelection {

  private final JinferOPTOptionsPanelController controller;
  private static final String DEFAULT_MENU_TEXT = "<none available>";
  private String iGGenerator;
  private String simplifier;
  private String schemaGenerator;

  private class IGGMenuItem {
    IGGenerator item;

    public IGGenerator get() {
      return item;
    }

    public IGGMenuItem(IGGenerator generator) {
      this.item = generator;
    }
    
    @Override
    public String toString() {
      return item.getModuleName();
    }
  }

  private class SimplifierMenuItem {
    Simplifier item;

    public Simplifier get() {
      return item;
    }

    public SimplifierMenuItem(Simplifier item) {
      this.item = item;
    }

    @Override
    public String toString() {
      return item.getModuleName();
    }
  }

  private class SchemaMenuItem {
    SchemaGenerator item;

    public SchemaGenerator get() {
      return item;
    }

    public SchemaMenuItem(SchemaGenerator item) {
      this.item = item;
    }

    @Override
    public String toString() {
      return item.getModuleName();
    }
  }

  JinferOPTPanel(JinferOPTOptionsPanelController controller) {
    this.controller = controller;
    initComponents();
    // TODO listen to changes in form fields and call controller.changed()
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jComboBox1 = new javax.swing.JComboBox();
    jComboBox2 = new javax.swing.JComboBox();
    jComboBox3 = new javax.swing.JComboBox();

    org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(JinferOPTPanel.class, "JinferOPTPanel.jLabel1.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(JinferOPTPanel.class, "JinferOPTPanel.jLabel2.text")); // NOI18N

    org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(JinferOPTPanel.class, "JinferOPTPanel.jLabel3.text")); // NOI18N

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(32, 32, 32)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addComponent(jLabel1)
          .addComponent(jLabel3))
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(240, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(178, Short.MAX_VALUE))
    );

    jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(JinferOPTPanel.class, "JinferOPTPanel.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
    );
  }// </editor-fold>//GEN-END:initComponents

  void load() {
    // read settings
    iGGenerator = NbPreferences.forModule(JinferOPTPanel.class).get("PreferredIGGenerator", DEFAULT_MENU_TEXT);
    simplifier = NbPreferences.forModule(JinferOPTPanel.class).get("PreferredSimplifier", DEFAULT_MENU_TEXT);
    schemaGenerator  = NbPreferences.forModule(JinferOPTPanel.class).get("PreferredSchemaGenerator", DEFAULT_MENU_TEXT);

    // init GUI
    jComboBox1.removeAllItems();
    jComboBox2.removeAllItems();
    jComboBox3.removeAllItems();

    for (IGGenerator ig : lookupIGGenerators()) {
      /* here we wrap the IGGenerator inside IGGMenuItem,
       * because jcombobox displays items by calling their toString() method
       * and since we don't know what the toString method of IGGenerator does..
       */
      jComboBox1.addItem(new IGGMenuItem(ig));
      if (iGGenerator.equals(ig.getModuleName()))
        jComboBox1.setSelectedIndex(jComboBox1.getItemCount()-1);
    }

    for (Simplifier s : lookupSimplifiers()) {
      jComboBox2.addItem(new SimplifierMenuItem(s));
      if (simplifier.equals(s.getModuleName()))
        jComboBox2.setSelectedIndex(jComboBox2.getItemCount()-1);
    }

    for (SchemaGenerator sg : lookupSchemaGenerators()) {
      jComboBox3.addItem(new SchemaMenuItem(sg));
      if (schemaGenerator.equals(sg.getModuleName()))
        jComboBox3.setSelectedIndex(jComboBox3.getItemCount()-1);
    }
  }

  void store() {
    iGGenerator = ((IGGMenuItem) jComboBox1.getSelectedItem()).toString();
    simplifier  = ((SimplifierMenuItem) jComboBox2.getSelectedItem()).toString();
    schemaGenerator = ((SchemaMenuItem) jComboBox3.getSelectedItem()).toString();

    NbPreferences.forModule(JinferOPTPanel.class).put("PreferredIGGenerator", iGGenerator);
    NbPreferences.forModule(JinferOPTPanel.class).put("PreferredSimplifier", simplifier);
    NbPreferences.forModule(JinferOPTPanel.class).put("PreferredSchemaGenerator", schemaGenerator);
  }

  boolean valid() {
    // TODO check whether form is consistent and complete
    return true;
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox jComboBox1;
  private javax.swing.JComboBox jComboBox2;
  private javax.swing.JComboBox jComboBox3;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTabbedPane jTabbedPane1;
  // End of variables declaration//GEN-END:variables

  public String getIGGenerator() {
    return iGGenerator;
  }

  public String getSimplifier() {
    return simplifier;
  }

  public String getSchemaGenerator() {
    return schemaGenerator;
  }

  private List<IGGenerator> lookupIGGenerators() {
    List<IGGenerator> list = new ArrayList<IGGenerator>();
    final Lookup lkp = Lookups.forPath("IGGeneratorProviders");

    for (IGGenerator ig : lkp.lookupAll(IGGenerator.class)) {
      list.add(ig);
    }
    
    if (list.size() == 0) {
      list.add(new IGGenerator() {

        public String getModuleName() {
          return DEFAULT_MENU_TEXT;
        }

        public void start(Input input, IGGeneratorCallback callback) {
          throw new UnsupportedOperationException("Not supported yet.");
        }
      });
    }

    return list;
  }

  private List<Simplifier> lookupSimplifiers() {
    List<Simplifier> list = new ArrayList<Simplifier>();
    final Lookup lkp = Lookups.forPath("SimplifierProviders");

    for (Simplifier s : lkp.lookupAll(Simplifier.class)) {
      list.add(s);
    }

    if (list.size() == 0) {
      list.add(new Simplifier() {

        public String getModuleName() {
          return DEFAULT_MENU_TEXT;
        }

        public void start(List<AbstractNode> initialGrammar, SimplifierCallback callback) {
          throw new UnsupportedOperationException("Not supported yet.");
        }
      });
    }

    return list;
  }

  private List<SchemaGenerator> lookupSchemaGenerators() {
    List<SchemaGenerator> list = new ArrayList<SchemaGenerator>();
    final Lookup lkp = Lookups.forPath("SchemaGeneratorProviders");
    for (SchemaGenerator sg : lkp.lookupAll(SchemaGenerator.class)) {
      list.add(sg);
    }
    if (list.size() == 0) {
      list.add(new SchemaGenerator() {
        public String getModuleName() {
          return DEFAULT_MENU_TEXT;
        }

        public void start(List<AbstractNode> grammar, SchemaGeneratorCallback callback) {
          throw new UnsupportedOperationException("Not supported yet.");
        }
      });
    }

    return list;
  }
}
