/*
 *  Copyright (C) 2010 anti
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cz.cuni.mff.ksi.jinfer.autoeditor.automatonvisualizer.layouts.graphviz.properties;

import cz.cuni.mff.ksi.jinfer.autoeditor.automatonvisualizer.layouts.graphviz.GraphvizLayoutFactory;
import cz.cuni.mff.ksi.jinfer.base.objects.AbstractPropertiesPanel;
import java.util.Properties;

/**
 * Properties panel for TwoStepSimplifierFactory.
 * @author anti
 */
public class GraphvizLayoutPropertiesPanel extends AbstractPropertiesPanel {

  private static final String DEFAULT_TEXT = "";
  private static final long serialVersionUID = 784463431L;

  /** Creates new form ModuleSelectionJPanel */
  public GraphvizLayoutPropertiesPanel(final Properties properties) {
    super(properties);
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    labelDotBin = new javax.swing.JLabel();
    txtDoBin = new javax.swing.JTextField();

    setMinimumSize(new java.awt.Dimension(500, 300));
    setPreferredSize(new java.awt.Dimension(500, 300));
    setLayout(new java.awt.GridBagLayout());

    labelDotBin.setText(org.openide.util.NbBundle.getMessage(GraphvizLayoutPropertiesPanel.class, "GraphvizLayoutPropertiesPanel.labelDotBin.text")); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 12);
    add(labelDotBin, gridBagConstraints);

    txtDoBin.setColumns(30);
    txtDoBin.setText(org.openide.util.NbBundle.getMessage(GraphvizLayoutPropertiesPanel.class, "GraphvizLayoutPropertiesPanel.txtDoBin.text")); // NOI18N
    add(txtDoBin, new java.awt.GridBagConstraints());
  }// </editor-fold>//GEN-END:initComponents

  @Override
  public final void load() {
    txtDoBin.setText(
            properties.getProperty(GraphvizLayoutFactory.PROPERTIES_DOTBIN, DEFAULT_TEXT));
  }

  @Override
  public void store() {
    properties.setProperty(GraphvizLayoutFactory.PROPERTIES_DOTBIN, txtDoBin.getText());
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel labelDotBin;
  private javax.swing.JTextField txtDoBin;
  // End of variables declaration//GEN-END:variables
}
