/*
 *  Copyright (C) 2010 rio
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cz.cuni.mff.ksi.jinfer.autoeditor.gui.component;

import cz.cuni.mff.ksi.jinfer.autoeditor.automatonvisualizer.StatePickingVisualizer;
import cz.cuni.mff.ksi.jinfer.autoeditor.automatonvisualizer.Visualizer;
import cz.cuni.mff.ksi.jinfer.base.automaton.State;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 * This class represents AutoEditor panel providing picking of one state
 * of displayed automaton.
 *
 * @author rio
 */
@SuppressWarnings({"PMD.SingularField"})
public class StatePickingComponent<T> extends AbstractComponent<T> {

  public StatePickingComponent() {
    super();
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings({"unchecked", "PMD"})
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();

    jLabel1.setText(org.openide.util.NbBundle.getMessage(StatePickingComponent.class, "StatePickingComponent.jLabel1.text")); // NOI18N

    jPanel1.setLayout(new java.awt.GridBagLayout());
    jScrollPane1.setViewportView(jPanel1);

    jLabel2.setText(org.openide.util.NbBundle.getMessage(StatePickingComponent.class, "StatePickingComponent.jLabel2.text")); // NOI18N

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
          .addComponent(jLabel1)
          .addComponent(jLabel2))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
        .addContainerGap())
    );
  }// </editor-fold>//GEN-END:initComponents
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables

  @Override
  public JPanel getAutomatonDrawPanel() {
    return jPanel1;
  }

  /**
   * Setter for {@link Visualizer} restricted to accept instances of {@link StatePickingVisualizer}.
   * @param visualizer
   */
  public void setVisualizer(final StatePickingVisualizer<T> visualizer) {
    super.setVisualizer(visualizer);
  }

  /**
   * Call this method after showing this component in AutoEditor to get a state
   * picked by user.
   *
   * @return Picked state.
   */
  public State<T> getPickedState() {
    final Visualizer<T> visualizer = getVisualizer();
    final ArrayList<State<T>> pickedList = new ArrayList<State<T>>(visualizer.getPickedVertexState().getPicked());

    // Clear picked state (any picked vertices) because this component may
    // be displayed in AutoEditor again and we do not want any vertices picked.
    visualizer.getPickedVertexState().clear();

    return pickedList.get(0);
  }

  /**
   * Set label text to display some information to user.
   *
   * @param text Text to display.
   */
  public void setLabel(final String text) {
    jLabel1.setText(text);
  }
}
