/*
 *  Copyright (C) 2010 anti
 * 
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 * 
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 * 
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package cz.cuni.mff.ksi.jinfer.crudemdl.processing.automatonmergingstate.simplifying.greedy.properties;

import cz.cuni.mff.ksi.jinfer.base.objects.AbstractPropertiesPanel;
import cz.cuni.mff.ksi.jinfer.base.utils.ModuleSelectionHelper;
import cz.cuni.mff.ksi.jinfer.crudemdl.processing.automatonmergingstate.conditiontesting.MergeConditionTesterFactory;
import cz.cuni.mff.ksi.jinfer.crudemdl.processing.automatonmergingstate.simplifying.greedy.AutomatonSimplifierGreedyFactory;
import java.util.Properties;
import javax.swing.DefaultComboBoxModel;

/**
 * TODO anti Comment!
 * @author anti
 */
public class AutomatonSimplifierGreedyPropertiesPanel extends AbstractPropertiesPanel {
  private static final String DEFAULT_MENU_TEXT = "<none available>";
  private static final long serialVersionUID = 784463431L;

  /** Creates new form ModuleSelectionJPanel */
  public AutomatonSimplifierGreedyPropertiesPanel(final Properties properties) {
    super(properties);
    initComponents();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    labelConditionTester = new javax.swing.JLabel();
    comboConditionTester = new javax.swing.JComboBox();
    jScrollPane3 = new javax.swing.JScrollPane();
    descContitionTester = new javax.swing.JTextPane();

    setMinimumSize(new java.awt.Dimension(600, 62));
    setPreferredSize(new java.awt.Dimension(600, 62));
    setLayout(new java.awt.GridBagLayout());

    labelConditionTester.setText("MergeConditionTester");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 12);
    add(labelConditionTester, gridBagConstraints);

    comboConditionTester.setMinimumSize(new java.awt.Dimension(400, 22));
    comboConditionTester.setPreferredSize(new java.awt.Dimension(400, 22));
    comboConditionTester.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comboConditionTesterChanged(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
    gridBagConstraints.insets = new java.awt.Insets(2, 12, 2, 2);
    add(comboConditionTester, gridBagConstraints);

    jScrollPane3.setViewportView(descContitionTester);

    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.gridwidth = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.ipady = 150;
    add(jScrollPane3, gridBagConstraints);
  }// </editor-fold>//GEN-END:initComponents

  private void comboConditionTesterChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboConditionTesterChanged
    // TODO add your handling code here:
    descContitionTester.setText(
            ModuleSelectionHelper.lookupImpl(MergeConditionTesterFactory.class,
            (String) comboConditionTester.getSelectedItem()).getDisplayModuleDescription()
            );
  }//GEN-LAST:event_comboConditionTesterChanged

  @Override
  public final void load() {
    comboConditionTester.setModel(new DefaultComboBoxModel(
            ModuleSelectionHelper.lookupNames(MergeConditionTesterFactory.class).toArray()
            ));
    comboConditionTester.setSelectedItem(properties.getProperty(AutomatonSimplifierGreedyFactory.PROPERTIES_CONDITION_TESTER, DEFAULT_MENU_TEXT));
    comboConditionTesterChanged(null);
  }

  @Override
  public void store() {
    properties.setProperty(AutomatonSimplifierGreedyFactory.PROPERTIES_CONDITION_TESTER,
            (String) comboConditionTester.getSelectedItem());
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox comboConditionTester;
  private javax.swing.JTextPane descContitionTester;
  private javax.swing.JScrollPane jScrollPane3;
  private javax.swing.JLabel labelConditionTester;
  // End of variables declaration//GEN-END:variables
}
